# Code generated by Github Copilot (https://copilot.github.com/) and modified by me

# given a csv file with Name of Customer, Food, and Quantity
# group the data by Food (case-insensitive) and sum the Quantity
# output the results to a new csv file
# and sort the result in alphabetical order by Food

# edit these variables!
CSV_FILE = 'supper_example.csv'
OUTPUT_FILE = 'orders_sorted_by_food_example.csv'

import csv

# open the csv file
with open(CSV_FILE, 'r') as f:
    # create a reader object
    reader = csv.reader(f)
    # create a dictionary
    d = {}
    # loop through the rows
    for row in reader:
        # if the food is in the dictionary
        if row[1].lower() in d:
            # add the quantity to the existing list
            d[row[1].lower()] += int(row[2])
        # if the food is not in the dictionary
        else:
            # add the food and quantity to the dictionary
            d[row[1].lower()] = int(row[2])

# open a new csv file
with open(OUTPUT_FILE, 'w') as f:
    # create a writer object
    writer = csv.writer(f)
    # loop through the dictionary
    for key, value in d.items():
        # write the food and quantity to the csv file
        writer.writerow([key, value])

# close the csv file
f.close()
