# Code generated by Github Copilot (https://copilot.github.com/) and modified by me

# given a csv file with Name of Customer, Food, and Quantity
# group the data by Name of Customer

# edit these variables!
CSV_FILE = 'supper_example.csv'
OUTPUT_FILE = 'orders_sorted_by_orderer_example.csv'

import csv

# open the csv file
with open(CSV_FILE, 'r') as f:
    # create a reader object
    reader = csv.reader(f)
    # create a dictionary
    d = {}
    # loop through the rows
    for row in reader:
        # if the name is in the dictionary
        if row[0] in d:
            # add the food and quantity to the existing list
            d[row[0]].append([row[1], int(row[2])])
        # if the name is not in the dictionary
        else:
            # add the name and food and quantity to the dictionary
            d[row[0]] = [[row[1], int(row[2])]]

# open a new csv file
with open(OUTPUT_FILE, 'w') as f:
    # create a writer object
    writer = csv.writer(f)
    # loop through the dictionary
    for key, value in d.items():
        # write the name and food and quantity to the csv file
        writer.writerow([key, value])

# close the csv file
f.close()
